### ISSUE TITLE
Make a plain compiled version for generic usage.

### ISSUE THREAD

**Issue by scssquatch** [encharm/xcase#1]
Would be nice to  have a compiled JS file so I can drop it into any project, instead of relying on node modules. Also registering it as a package on Bower would be awesome.

**Comment by Rush** [comment]
Added xcase to bower and added a `dist` directory with precompiled standalone modules. You can just load the script and use `xcase.camelize`. Anything else?

**Comment by scssquatch** [comment]
Wow that was fast. Nope that's all! Thank you so much!

**Comment by Rush** [comment]
Sure thing. Please re-open this ticket if you find any issues.
